### ISSUE TITLE
python3 de ve diger son surumlerde calismiyor setup.py. uyumluluk sorununu gidermelisin. str sorunu var halledersin.

### ISSUE THREAD

**Issue by mehmetnail0** [AzizKpln/walterRat#4]
https://github.com/AzizKpln/walterRat/blob/a37f0401f81533d38406f19415ed92c25aeaeb83/setup.py#L6

**Comment by AzizKpln** [comment]
Hayır sorun yok python2 uyumlu yazdım kardeşim python3 değil python2 ile çalıştırmalısın
